<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class commande extends Model
{
    protected $table = 'commande';
    protected $primaryKey = 'id_commande';
    protected $keyType = 'string';
    public $timestamps = true;
    protected $fillable = [
        'id_commande',
        'id_utilisateur',
        'montant_total',
        'date_commande',
        'points_gagne'
    ];

    public static function listeToutesCommandes(){
        return self::all();
    }

    public function utilisateur(){
        return $this->belongsTo(Utilisateur::class, 'id_utilisateur', 'id_utilisateur');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
           do{
               $model->id_commande = 'CMD' . str_pad(mt_rand(1, 999999), 6, '0', STR_PAD_LEFT);
           } while (self::where('id_commande', $model->id_commande)->exists());
        });
    }

}
