<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;

class employe extends Model
{
    protected $table = 'employe';
    protected $primaryKey = 'id_employe';
    protected $keyType = 'string';
    public $timestamps = true;
    protected $fillable = [
        'id_employe',
        'nom_employe',
        'email_employe',
        'mot_de_passe_employe',
        'date_embauche'
    ];

    public function setMotDePasseEmployeAttribute($value){
        $this->attributes['mot_de_passe_employe'] = Hash::make($value);
    }

    public static function getAllEmployes()
    {
      return  self::all();
    }

    public function deleteEmploye($id_employe){

        $employe = self::find($id_employe);

      return  $employe->delete();

    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model) {
            do{
                $model->id_employe = 'Emp' . str_pad(mt_rand(1, 999999), 6, '0', STR_PAD_LEFT);
            }while (self::where('id_employe', $model->id_employe)->exists());
        });
    }

}
